# Generated by Django 2.1.3 on 2018-12-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodssku',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='goodstype',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indexgoodsbanner',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indexpromotionbanner',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='indextypegoodsbanner',
            old_name='update_tim',
            new_name='update_time',
        ),
    ]
