# Generated by Django 2.1.3 on 2018-12-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181206_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='update_tim',
            new_name='update_time',
        ),
    ]
