# Generated by Django 2.1.3 on 2018-12-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='update_tim',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_tim',
            new_name='update_time',
        ),
    ]
